#include "MarketDataMessage.h"

Tick::Tick(CThostFtdcDepthMarketDataField* pDepthMarketData) :
    instrumentID(pDepthMarketData->InstrumentID),
    updateTime(pDepthMarketData->UpdateTime),
    lastPrice(pDepthMarketData->LastPrice),
    preClose(pDepthMarketData->PreClosePrice),
    bidPrice1(pDepthMarketData->BidPrice1),
    bidPrice2(pDepthMarketData->BidPrice2),
    bidPrice3(pDepthMarketData->BidPrice3),
    bidPrice4(pDepthMarketData->BidPrice4),
    bidPrice5(pDepthMarketData->BidPrice5),
    askPrice1(pDepthMarketData->AskPrice1),
    askPrice2(pDepthMarketData->AskPrice2),
    askPrice3(pDepthMarketData->AskPrice3),
    askPrice4(pDepthMarketData->AskPrice4),
    askPrice5(pDepthMarketData->AskPrice5),
    bidVolume1(pDepthMarketData->BidVolume1),
    bidVolume2(pDepthMarketData->BidVolume2),
    bidVolume3(pDepthMarketData->BidVolume3),
    bidVolume4(pDepthMarketData->BidVolume4),
    bidVolume5(pDepthMarketData->BidVolume5),
    askVolume1(pDepthMarketData->AskVolume1),
    askVolume2(pDepthMarketData->AskVolume2),
    askVolume3(pDepthMarketData->AskVolume3),
    askVolume4(pDepthMarketData->AskVolume4),
    askVolume5(pDepthMarketData->AskVolume5),
    accumulatedVolume(pDepthMarketData->Volume),
    openInterest(pDepthMarketData->OpenInterest),
    turnOver(pDepthMarketData->Turnover),
    open(pDepthMarketData->OpenPrice),
    high(pDepthMarketData->HighestPrice),
    low(pDepthMarketData->LowestPrice),
    upperLimitPrice(pDepthMarketData->UpperLimitPrice),
    lowerLimitPrice(pDepthMarketData->LowerLimitPrice) {}
